### ISSUE TITLE
Feature Request: include prices by item and search engine/website

### ISSUE THREAD

**Issue by RuubixO** [Benzhaomin/bdiefinder#6]
Hi there,

This is an incredibly helpful tool--thank you! It would be extremely helpful to also glance at current prices after I narrow my search, so I don't have to go in and out of links for each website for every ram stick I want to check out.

-Ruubix

**Comment by Benzhaomin** [comment]
Hey, while I do see the merit in that idea there's a technical barrier I'm not looking to jump just yet.

For reference, here's my reply to a similiar idea on Reddit https://www.reddit.com/r/Amd/comments/8clf15/bdie_finder/dxh2oah/

This issue can stay open in case somebody wants to propose a clean implementation of that idea. It would have to be retailer agnostic and run client-side.

Thanks for your interest

**Comment by RuubixO** [comment]
I hadn't thought about APIs and that makes complete sense. I saw that pcpartpicker allowed non-commercial use of their data and that might simplify the meta search. Keep up the great work.

**Comment by dasbuilder** [comment]
What I just did was I copied the text:

I first took the Amazon search URL and made it a Python variable while also removing the %s:
`abase = "https://www.amazon.com/s/field-keywords="`

I then took the list the of models from the github.io project page and made that a variable too:

![pyvars](https://xavierlight.s3.amazonaws.com/monosnap/71b9s_29-05-2018_03-00-59.png)

The rest of the screenshot shows the flow of commands as I take the input and make into a link that can then copy and pasted into browser. 
While it's not that efficient because I have to manually copy and paste links, it still allows me to easily generate the link. 

![searchresult](https://xavierlight.s3.amazonaws.com/monosnap/wy5f0_29-05-2018_03-07-56.png)

**Comment by dasbuilder** [comment]
I'm also working to see what kind of information I can get from pcpartpicker's site for prices because it is likely they are using some type of API or other system to pull prices from NewEgg and Amazon. 
I'm not affiliated with this project but know how to gather information from websites by way of Python.

**Comment by Benzhaomin** [comment]
@dasbuilder thanks for looking into it, keep us posted if you make progress

**Comment by dasbuilder** [comment]
Bdiefinder only has a list of these SKUs in a JS file [linked here] (https://raw.githubusercontent.com/Benzhaomin/bdiefinder/master/src/js/data.js) which loads on their main page. 

I'm not sure how this list was originally put together but suffice to say that if the list ever changes, how is that updated?

**Comment by Benzhaomin** [comment]
That list mostly comes from [hardwareluxx.de](https://www.hardwareluxx.de/community/f13/die-ultimative-hardwareluxx-samsung-8gb-b-die-liste-alle-hersteller-07-05-18-a-1161530.html). It was built manually and is updated manually when I get DMs on Reddit or PRs on GitHub. It's not ideal but at least I can try to vet SKU additions and guarantee that only B-Dies are listed.
